version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `package-lock.json` in the `root` directory
    directory: "/"
    # Schedule updates
    schedule:
      interval: "weekly"
